---
# BrainCraft.io YAML Lint Configuration
extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
