apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: konductor-vm

resources:
  - namespace.yaml
  - konductor.yaml

# Override namespace for all resources
namespace: konductor

# Common labels applied to all resources
labels:
  - pairs:
      app.kubernetes.io/name: konductor
      app.kubernetes.io/component: virtual-machine
      app.kubernetes.io/part-of: konductor
    includeSelectors: false
